title: Chaitya Shah's Blog
description: Chaitya Shah’s journey in the fascinating world of Computer Science. Chaitya talks about his experiences and tutorials. He likes to share with the world. Programming, Machine Learning, Development, College Life you name it, it’s all there.
show_downloads: false

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://chaitya62.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

github:
  owner_name: "Chaitya Shah"
  owner_url: "https://github.com/chaitya62"

google_analytics: true


# social
author: "Chaitya Shah"
image: /thumbnail-jumbo.png
twitter:
  username: Chaitya_chase
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:
